server:
  port: 4020

spring:
  application:
    name: Core Interaction System

  datasource:
    url: jdbc:postgresql://localhost:5432/core_integration_system
    username: postgres
    password: nosferratu
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:db/changelog-master.xml
    enabled: true

  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 1000ms
      database: 0

resilience4j:
  ratelimiter:
    instances:
      accountsRateLimiter:
        limitForPeriod: 5
        limitRefreshPeriod: 1s
        timeoutDuration: 500ms

      accountsBulkRateLimiter:
        limitForPeriod: 2
        limitRefreshPeriod: 2s
        timeoutDuration: 700ms

      loansRateLimiter:
        limitForPeriod: 3
        limitRefreshPeriod: 2s
        timeoutDuration: 300ms

      loansBulkRateLimiter:
        limitForPeriod: 2
        limitRefreshPeriod: 3s
        timeoutDuration: 700ms

      balancesRateLimiter:
        limitForPeriod: 10
        limitRefreshPeriod: 1s
        timeoutDuration: 200ms

      balancesBulkRateLimiter:
        limitForPeriod: 5
        limitRefreshPeriod: 2s
        timeoutDuration: 500ms

      debitCardsRateLimiter:
        limitForPeriod: 7
        limitRefreshPeriod: 1s
        timeoutDuration: 300ms

      debitCardsBulkRateLimiter:
        limitForPeriod: 3
        limitRefreshPeriod: 2s
        timeoutDuration: 500ms

      legalEntitiesRateLimiter:
        limitForPeriod: 4
        limitRefreshPeriod: 2s
        timeoutDuration: 400ms

      legalEntitiesBulkRateLimiter:
        limitForPeriod: 2
        limitRefreshPeriod: 3s
        timeoutDuration: 600ms

      limitsRateLimiter:
        limitForPeriod: 6
        limitRefreshPeriod: 1s
        timeoutDuration: 250ms

      limitsBulkRateLimiter:
        limitForPeriod: 3
        limitRefreshPeriod: 2s
        timeoutDuration: 500ms
  circuitbreaker:
    instances:
      getAccountDetailsByAccountIds:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slidingWindowSize: 10
        waitDurationInOpenState: 30s
      getBalancesByAccountIds:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slidingWindowSize: 10
        waitDurationInOpenState: 30s
      getDebitCarsByAccountIds:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slidingWindowSize: 10
        waitDurationInOpenState: 30s
      getLegalEntitiesByAccountIds:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slidingWindowSize: 10
        waitDurationInOpenState: 30s
      getLimitsByAccountIds:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slidingWindowSize: 10
        waitDurationInOpenState: 30s
      getLoansByAccountIds:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slidingWindowSize: 10
        waitDurationInOpenState: 30s
logging:
  level:
    root: INFO
    com.coreintegration: DEBUG
