openapi: 3.0.3
info:
  title: Account
  version: v1
servers:
  - url: /service-api/v1/accounts

paths:
  /:
    get:
      summary: Get list of account
      tags:
        - Accounts
      parameters:
        - in: query
          name: page
          schema:
            type: integer
          required: false
        - in: query
          name: size
          schema:
            type: integer
          required: false
      responses:
        '200':
          description: Successful operation
  /{id}:
    get:
      summary: Get a single account
      tags:
        - Accounts
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation

components:
  schemas:
    Account:
      type: object
      properties:
        id:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        surname:
          type: string
        legalEntities:
          type: array
          items:
            $ref: '#/components/schemas/LegalEntity'
        balance:
          $ref: '#/components/schemas/Balance'
        debitCards:
          type: array
          items:
            $ref: '#/components/schemas/DebitCard'
    LegalEntity:
      $ref: "./schemas/legal-entity.yaml"
    Balance:
      $ref: "./schemas/balance.yaml"
    DebitCard:
      $ref: "./schemas/debit-card.yaml"

