openapi: 3.0.3
info:
  title: Balance
  version: v1
servers:
  - url: /service-api/v1/balances

paths:
  /:
    get:
      summary: Get balances by account ids
      operationId: getBalancesByAccountIds
      tags:
        - Balances
      parameters:
        - name: accountIds
          in: query
          required: true
          style: form
          explode: true
          schema:
            type: array
            items:
              type: string
              format: uuid
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BalanceListResponse'
  /{accountId}:
    get:
      summary: Get balance by account id
      operationId: getBalanceByAccountId
      tags:
        - Balances
      parameters:
        - name: accountId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BalanceResponse'

components:
  schemas:
    BalanceResponse:
      $ref: "./schemas/response/balance-response.yaml"
    BalanceListResponse:
      $ref: "./schemas/response/balance-list-response.yaml"
    Balance:
      $ref: "./schemas/model/balance.yaml"
