openapi: 3.0.3
info:
  title: DebitCard
  version: v1
servers:
  - url: /service-api/v1/debit-cards

paths:
  /:
    get:
      summary: Get debit cards by account ids
      operationId: getDebitCardsByAccountIds
      tags:
        - DebitCards
      parameters:
        - name: accountIds
          in: query
          required: true
          style: form
          explode: true
          schema:
            type: array
            items:
              type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DebitCardListResponse'
  /{accountId}:
    get:
      summary: Get a single debitcard
      operationId: getDebitCardsByAccountId
      tags:
        - DebitCards
      parameters:
        - name: accountId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DebitCardResponse'

components:
  schemas:
    DebitCardResponse:
      $ref: "./schemas/response/debit-cards-response.yaml"
    DebitCardListResponse:
      $ref: "./schemas/response/debit-cards-list-response.yaml"
    DebitCard:
      $ref: "./schemas/model/debit-card.yaml"
