openapi: 3.0.3
info:
  title: LegalEntity
  version: v1
servers:
  - url: /service-api/v1/legal-entities

paths:
  /:
    get:
      summary: Get list of legalentity
      parameters:
        - in: query
          name: page
          schema:
            type: integer
          required: false
        - in: query
          name: size
          schema:
            type: integer
          required: false
      responses:
        '200':
          description: Successful operation
  /{id}:
    get:
      summary: Get a single legalentity
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation

components:
  schemas:
    LegalEntity:
      $ref: "./schemas/legal-entity.yaml"
