openapi: 3.0.3
info:
  title: LegalEntity
  version: v1
servers:
  - url: /service-api/v1/legal-entities

paths:
  /service-api/v1/legal-entities:
    get:
      summary: Get list of legal entities by account ids
      operationId: getLegalEntitiesByAccountIds
      tags:
        - LegalEntities
      parameters:
        - name: accountIds
          in: query
          required: true
          style: form
          explode: true
          schema:
            type: array
            items:
              type: string
              format: uuid
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LegalEntitiesListResponse'
  /service-api/v1/legal-entities/{accountId}:
    get:
      summary: get legal entities by account id
      operationId: getLegalEntitiesByAccountId
      tags:
        - LegalEntities
      parameters:
        - name: accountId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LegalEntitiesResponse'

components:
  schemas:
    LegalEntitiesResponse:
      $ref: "./schemas/response/legal-entities-response.yaml"
    LegalEntitiesListResponse:
      $ref: "./schemas/response/legal-entities-list-response.yaml"
    LegalEntity:
      $ref: "./schemas/model/legal-entity.yaml"
