openapi: 3.0.3
info:
  title: Limit
  version: v1
servers:
  - url: /service-api/v1/limits

paths:
  /:
    get:
      summary: Get list of limits by account ids
      operationId: getLimitsByAccountIds
      tags:
        - Limits
      parameters:
        - name: accountIds
          in: query
          required: true
          schema:
            type: array
            items:
              type: string
              format: uuid
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LimitsListResponse'
  /{accountId}:
    get:
      summary: get limits by account id
      operationId: getLimitsByAccountId
      tags:
        - Limits
      parameters:
        - name: accountId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LimitsResponse'

components:
  schemas:
    LimitsResponse:
      $ref: "./schemas/response/limits-response.yaml"
    LimitsListResponse:
      $ref: "./schemas/response/limits-list-response.yaml"
    Limit:
      $ref: "./schemas/model/limit.yml"
