openapi: 3.0.3
info:
  title: Loan
  version: v1
servers:
  - url: /service-api/v1/loans

paths:
  /service-api/v1/loans:
    get:
      summary: Get list of loans by account ids
      operationId: getLoansByAccountIds
      tags:
        - Loans
      parameters:
        - name: accountIds
          in: query
          required: true
          style: form
          explode: true
          schema:
            type: array
            items:
              type: string
              format: uuid
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoansListResponse'
  /service-api/v1/loans/{accountId}:
    get:
      summary: get loans by account id
      operationId: getLoansByAccountId
      tags:
        - Loans
      parameters:
        - name: accountId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoansResponse'

components:
  schemas:
    LoansResponse:
      $ref: "./schemas/response/loans-response.yaml"
    LoansListResponse:
      $ref: "./schemas/response/loans-list-response.yaml"
    Loan:
      $ref: "./schemas/model/loan.yaml"